//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManagement.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.SectionSchedule = new HashSet<SectionSchedule>();
        }
    
        public int ID { get; set; }
        public int DayOfWeekID { get; set; }
        public int idTimeHour { get; set; }
        public Nullable<int> idTimeMin { get; set; }
    
        public virtual DayOfWeeks DayOfWeeks { get; set; }
        public virtual TimeHour TimeHour { get; set; }
        public virtual TimeMinutes TimeMinutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionSchedule> SectionSchedule { get; set; }
    }
}
