//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManagement.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Teacher
    {
        public int idTeacher { get; set; }
        public int idSection { get; set; }
        public Nullable<bool> isActive { get; set; }
        public int id { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
